#ifndef DIRSTAT_CORE_H
#define DIRSTAT_CORE_H

/* Generated by cbindgen from dirstat-core. Do not edit by hand; run `cbindgen -o include/dirstat_core.h`. */

#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>

// Bump on every ABI change; the Swift wrapper refuses to run against a
// mismatched header/library pair (CORE-FFI-SAFE-3 / APP-FFI-6).
#define DS_ABI_VERSION 1

// Node flag bits mirrored into the C header (values asserted equal to the
// internal `tree::flags` constants by a unit test).
#define DS_NODE_FLAG_HIDDEN 1

#define DS_NODE_FLAG_HARDLINK_DUP 2

#define DS_NODE_FLAG_UNREADABLE 4

#define DS_NODE_FLAG_SCANNING 8

typedef struct DsModel DsModel;

typedef struct DsScan DsScan;

// Scan options; zero-initialize for defaults.
typedef struct DsScanOptions {
  uint8_t cross_filesystems;
  uint8_t follow_symlinks;
  uint8_t exclude_hidden;
  uint32_t max_concurrency;
} DsScanOptions;

// Live scan totals for progress polling.
typedef struct DsScanStats {
  uint64_t items;
  uint64_t bytes;
  uint8_t complete;
  uint64_t error_count;
} DsScanStats;

// Flat per-node facts (CORE-FFI-4). Strings via `ds_node_name`/`ds_node_path`.
typedef struct DsNodeInfo {
  uint64_t id;
  uint64_t parent;
  uint64_t logical;
  uint64_t physical;
  uint64_t files;
  uint64_t subdirs;
  uint64_t items;
  int64_t mtime;
  uint32_t child_count;
  uint32_t flags;
  // 0 file, 1 dir, 2 symlink.
  uint8_t kind;
  // Kind bucket (design 1g); see `ds_category_name`.
  uint8_t category;
  // 0 this week … 4 older (vs scan start).
  uint8_t age_bucket;
  // 0..11 top-12 extension slot, 12 = other/none (CORE-EXT-3).
  uint8_t ext_slot;
} DsNodeInfo;

// Per-extension aggregate (CORE-EXT-*).
typedef struct DsTypeStat {
  // Lowercased extension, NUL-terminated, truncated to fit.
  char ext[16];
  uint64_t logical;
  uint64_t files;
  // 0..11 distinct palette slot, 12 = aggregated "other".
  uint8_t slot;
} DsTypeStat;

// Per-category aggregate for the legend chips / capacity footer (1b).
typedef struct DsCategoryStat {
  uint8_t category;
  uint64_t logical;
  uint64_t files;
} DsCategoryStat;

// Volume reconciliation figures (CORE-SYN-2/3).
typedef struct DsVolumeInfo {
  uint64_t total;
  uint64_t free;
  // `max(0, total - free - measured)` — the "unreadable" number.
  uint64_t unknown;
} DsVolumeInfo;

// One treemap rectangle (bulk buffer element).
typedef struct DsTmRect {
  uint64_t node;
  float x;
  float y;
  float w;
  float h;
  uint16_t depth;
  uint8_t is_dir;
  uint8_t category;
  uint8_t age_bucket;
  uint8_t ext_slot;
} DsTmRect;





#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

// ABI version of this library; compare with `DS_ABI_VERSION` in the header
// you compiled against before calling anything else.
uint32_t ds_abi_version(void);

// Retrieve (and keep) the calling thread's last error message.
// Two-call pattern; returns bytes needed including NUL, 0 if no error.
int32_t ds_last_error(char *buf, size_t cap);

// Start scanning `root_utf8`. Returns NULL on error (see `ds_last_error`).
// `options` may be NULL for defaults. The callback (nullable) fires on
// engine threads (CORE-FFI-2).
struct DsScan *ds_scan_begin(const char *root_utf8,
                             const struct DsScanOptions *options,
                             void (*callback)(uint64_t items,
                                              uint64_t bytes,
                                              const char *path,
                                              uint8_t done,
                                              void *user),
                             void *user);

// Request cancellation (CORE-SCAN-11). Partial results remain valid.
void ds_scan_cancel(struct DsScan *scan);

uint8_t ds_scan_is_complete(const struct DsScan *scan);

// Block until the scan finishes (`scan_await`).
void ds_scan_join(struct DsScan *scan);

// Get a model handle. Safe to call while the scan runs (progressive reads);
// each returned handle must be freed with `ds_model_free`.
struct DsModel *ds_scan_model(const struct DsScan *scan);

// Free the scan handle. Cancels and joins if still running (the model, if
// retained via `ds_scan_model`, stays valid).
void ds_scan_free(struct DsScan *scan);

// Free a model handle (CORE-FFI-3). NodeIds from it are invalid after.
void ds_model_free(struct DsModel *model);

// Root node id (always 1 for a non-empty model; 0 = empty/invalid).
uint64_t ds_model_root(const struct DsModel *model);

int32_t ds_model_stats(const struct DsModel *model, struct DsScanStats *out);

int32_t ds_node_info(const struct DsModel *model, uint64_t id, struct DsNodeInfo *out);

// Node display name. Two-call pattern; returns needed bytes incl. NUL,
// negative on error.
int32_t ds_node_name(const struct DsModel *model, uint64_t id, char *buf, size_t cap);

// Absolute filesystem path of a node. Two-call pattern.
int32_t ds_node_path(const struct DsModel *model, uint64_t id, char *buf, size_t cap);

// Sorted children (CORE-TREE-3). `sort`: 0 size, 1 name, 2 items, 3 mtime.
// Fills up to `cap` ids into `buf`; returns the total child count
// (call again with a bigger buffer if total > cap), negative on error.
int64_t ds_node_children(const struct DsModel *model,
                         uint64_t id,
                         uint8_t sort,
                         uint8_t descending,
                         uint64_t *buf,
                         size_t cap);

double ds_node_percent_of_root(const struct DsModel *model, uint64_t id);

double ds_node_percent_of_parent(const struct DsModel *model, uint64_t id);

// Extension aggregation sorted bytes-desc (CORE-EXT-2). Fills up to `cap`
// entries; returns total distinct extensions, negative on error.
int64_t ds_type_list(const struct DsModel *model, struct DsTypeStat *buf, size_t cap);

// Per-category totals over the whole tree (design 1b legend chips / 1g).
// `buf` should hold 8 entries; returns the count written (8), sorted
// bytes-desc.
int64_t ds_category_list(const struct DsModel *model, struct DsCategoryStat *buf, size_t cap);

// Stable English name for a category id (hosts localize their own).
int32_t ds_category_name(uint8_t category, char *buf, size_t cap);

int32_t ds_model_set_volume(const struct DsModel *model, uint64_t total, uint64_t free);

int32_t ds_model_volume(const struct DsModel *model, struct DsVolumeInfo *out);

// Error message + path for report entry `index`. Two-call pattern.
int32_t ds_model_error(const struct DsModel *model, uint64_t index, char *buf, size_t cap);

// Lay out the subtree under `root` into a `w × h` rectangle at origin.
// `algorithm`: 0 KDirStat rows, 1 squarified. On success writes an
// engine-owned buffer to `(out, out_len)`; free with `ds_treemap_free`.
int32_t ds_treemap_layout(const struct DsModel *model,
                          uint64_t root,
                          float w,
                          float h,
                          uint8_t algorithm,
                          float min_px,
                          struct DsTmRect **out,
                          size_t *out_len);

// Free a layout buffer returned by `ds_treemap_layout`.
void ds_treemap_free(struct DsTmRect *rects, size_t len);

// Hit-test a laid-out buffer (CORE-TM-4). Returns the deepest containing
// leaf's node id, 0 if none.
uint64_t ds_treemap_hit_test(const struct DsTmRect *rects, size_t len, float x, float y);

// Re-read one node and its subtree from disk (after the host mutated the
// filesystem, e.g. Move to Trash), updating ancestors. Synchronous.
int32_t ds_refresh_node(const struct DsModel *model, uint64_t id);

// Deliberately panics internally; must return -1 and set the error rather
// than unwind across the boundary. Exists for the FFI-safety eval.
int32_t ds_internal_panic_test(void);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* DIRSTAT_CORE_H */
